name: OWASP ZAP Security Scan

on:
  schedule:
    # Run the scan weekly on Sunday at 1 AM
    - cron: '0 1 * * 0'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  zap-baseline-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'https://www.bitrab.online/'
          # The following are optional configurations
          rules_file_name: '.github/workflows/zap-rules.tsv'
          cmd_options: '-a -j'
          allow_issue_writing: true
          issue_title: 'ZAP Scan Report'
          token: ${{ secrets.GITHUB_TOKEN }}
          
  zap-full-scan:
    runs-on: ubuntu-latest
    needs: [zap-baseline-scan]
    # Only run full scan when manually triggered
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://www.bitrab.online/'
          # The following are optional configurations
          rules_file_name: '.github/workflows/zap-rules.tsv'
          cmd_options: '-a -j'
          allow_issue_writing: true
          issue_title: 'ZAP Full Scan Report'
          token: ${{ secrets.GITHUB_TOKEN }} 