name: OWASP ZAP Security Scan

on:
  schedule:
    # Run the scan weekly on Sunday at 1 AM
    - cron: '0 1 * * 0'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      full_scan:
        description: 'Run full scan (includes active attacks)'
        required: false
        default: false
        type: boolean

# Add permissions to allow issue creation
permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  zap-baseline-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'https://www.bitrab.online/'
          # The following are optional configurations
          rules_file_name: '.github/assets/zap-rules.tsv'
          cmd_options: '-a -j -T 10 -z "-config ajaxSpider.maxDuration=10"'
          allow_issue_writing: true
          issue_title: 'ZAP Baseline Scan Report'
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'zap-baseline-scan-report'
          
  zap-full-scan:
    runs-on: ubuntu-latest
    needs: [zap-baseline-scan]
    # Only run full scan when manually triggered with the full_scan input set to true
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.full_scan == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://www.bitrab.online/'
          # The following are optional configurations
          rules_file_name: '.github/assets/zap-rules.tsv'
          cmd_options: '-a -j -T 15 -z "-config ajaxSpider.maxDuration=20 -config ajaxSpider.clickDefaultElems=true"'
          allow_issue_writing: true
          issue_title: 'ZAP Full Scan Report'
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'zap-full-scan-report'
      
#   zap-api-scan:
#     runs-on: ubuntu-latest
#     # Only run API scan when manually triggered with the full_scan input set to true
#     if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.full_scan == 'true' }}
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
        
#       - name: ZAP API Scan
#         uses: zaproxy/action-api-scan@v0.5.0
#         with:
#           target: 'https://www.bitrab.online/php/'
#           # API Definition configuration - for REST APIs
#           # format: openapi
#           # file_name: './path/to/openapi.yaml'
#           cmd_options: '-a -j'
#           allow_issue_writing: true
#           issue_title: 'ZAP API Scan Report'
#           token: ${{ secrets.GITHUB_TOKEN }}
#           artifact_name: 'zap-api-scan-report' 